onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_minimicro/top_level/PC_i/clk
add wave -noupdate /tb_minimicro/top_level/PC_i/rst_n
add wave -noupdate /tb_minimicro/top_level/PC_i/pc_sel
add wave -noupdate /tb_minimicro/top_level/PC_i/pc_imm
add wave -noupdate /tb_minimicro/top_level/PC_i/pc_out
add wave -noupdate -divider im
add wave -noupdate /tb_minimicro/top_level/Instruction_memory_i/address
add wave -noupdate /tb_minimicro/top_level/Instruction_memory_i/instruction
add wave -noupdate -divider rf
add wave -noupdate /tb_minimicro/top_level/RF_i/clk
add wave -noupdate /tb_minimicro/top_level/RF_i/rst_n
add wave -noupdate /tb_minimicro/top_level/RF_i/we
add wave -noupdate -radix unsigned -childformat {{{/tb_minimicro/top_level/RF_i/rs1[3]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/rs1[2]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/rs1[1]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/rs1[0]} -radix unsigned}} -expand -subitemconfig {{/tb_minimicro/top_level/RF_i/rs1[3]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/rs1[2]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/rs1[1]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/rs1[0]} {-radix unsigned}} /tb_minimicro/top_level/RF_i/rs1
add wave -noupdate -radix unsigned -childformat {{{/tb_minimicro/top_level/RF_i/rs2[3]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/rs2[2]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/rs2[1]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/rs2[0]} -radix unsigned}} -expand -subitemconfig {{/tb_minimicro/top_level/RF_i/rs2[3]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/rs2[2]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/rs2[1]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/rs2[0]} {-radix unsigned}} /tb_minimicro/top_level/RF_i/rs2
add wave -noupdate -radix unsigned -childformat {{{/tb_minimicro/top_level/RF_i/rd[3]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/rd[2]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/rd[1]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/rd[0]} -radix unsigned}} -expand -subitemconfig {{/tb_minimicro/top_level/RF_i/rd[3]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/rd[2]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/rd[1]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/rd[0]} {-radix unsigned}} /tb_minimicro/top_level/RF_i/rd
add wave -noupdate -radix unsigned -childformat {{{/tb_minimicro/top_level/RF_i/d[15]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/d[14]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/d[13]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/d[12]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/d[11]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/d[10]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/d[9]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/d[8]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/d[7]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/d[6]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/d[5]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/d[4]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/d[3]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/d[2]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/d[1]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/d[0]} -radix unsigned}} -expand -subitemconfig {{/tb_minimicro/top_level/RF_i/d[15]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/d[14]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/d[13]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/d[12]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/d[11]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/d[10]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/d[9]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/d[8]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/d[7]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/d[6]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/d[5]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/d[4]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/d[3]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/d[2]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/d[1]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/d[0]} {-radix unsigned}} /tb_minimicro/top_level/RF_i/d
add wave -noupdate -radix unsigned -childformat {{{/tb_minimicro/top_level/RF_i/qs1[15]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs1[14]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs1[13]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs1[12]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs1[11]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs1[10]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs1[9]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs1[8]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs1[7]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs1[6]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs1[5]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs1[4]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs1[3]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs1[2]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs1[1]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs1[0]} -radix unsigned}} -expand -subitemconfig {{/tb_minimicro/top_level/RF_i/qs1[15]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/qs1[14]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/qs1[13]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/qs1[12]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/qs1[11]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/qs1[10]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/qs1[9]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/qs1[8]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/qs1[7]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/qs1[6]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/qs1[5]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/qs1[4]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/qs1[3]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/qs1[2]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/qs1[1]} {-radix unsigned} {/tb_minimicro/top_level/RF_i/qs1[0]} {-radix unsigned}} /tb_minimicro/top_level/RF_i/qs1
add wave -noupdate -radix unsigned -childformat {{{/tb_minimicro/top_level/RF_i/qs2[15]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs2[14]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs2[13]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs2[12]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs2[11]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs2[10]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs2[9]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs2[8]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs2[7]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs2[6]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs2[5]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs2[4]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs2[3]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs2[2]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs2[1]} -radix unsigned} {{/tb_minimicro/top_level/RF_i/qs2[0]} -radix unsigned}} -expand -subitemconfig {{/tb_minimicro/top_level/RF_i/qs2[15]} {-height 15 -radix unsigned} {/tb_minimicro/top_level/RF_i/qs2[14]} {-height 15 -radix unsigned} {/tb_minimicro/top_level/RF_i/qs2[13]} {-height 15 -radix unsigned} {/tb_minimicro/top_level/RF_i/qs2[12]} {-height 15 -radix unsigned} {/tb_minimicro/top_level/RF_i/qs2[11]} {-height 15 -radix unsigned} {/tb_minimicro/top_level/RF_i/qs2[10]} {-height 15 -radix unsigned} {/tb_minimicro/top_level/RF_i/qs2[9]} {-height 15 -radix unsigned} {/tb_minimicro/top_level/RF_i/qs2[8]} {-height 15 -radix unsigned} {/tb_minimicro/top_level/RF_i/qs2[7]} {-height 15 -radix unsigned} {/tb_minimicro/top_level/RF_i/qs2[6]} {-height 15 -radix unsigned} {/tb_minimicro/top_level/RF_i/qs2[5]} {-height 15 -radix unsigned} {/tb_minimicro/top_level/RF_i/qs2[4]} {-height 15 -radix unsigned} {/tb_minimicro/top_level/RF_i/qs2[3]} {-height 15 -radix unsigned} {/tb_minimicro/top_level/RF_i/qs2[2]} {-height 15 -radix unsigned} {/tb_minimicro/top_level/RF_i/qs2[1]} {-height 15 -radix unsigned} {/tb_minimicro/top_level/RF_i/qs2[0]} {-height 15 -radix unsigned}} /tb_minimicro/top_level/RF_i/qs2
add wave -noupdate -divider cu
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/flags
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/op_code
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/branch
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/alu_op
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/writeback_sel
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/rtype_sel
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/dm_we
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/rf_we
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/pc_sel
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/rs2_sel
add wave -noupdate -divider PC
add wave -noupdate /tb_minimicro/top_level/PC_i/clk
add wave -noupdate /tb_minimicro/top_level/PC_i/rst_n
add wave -noupdate /tb_minimicro/top_level/PC_i/pc_sel
add wave -noupdate -radix unsigned /tb_minimicro/top_level/PC_i/pc_imm
add wave -noupdate -radix unsigned /tb_minimicro/top_level/PC_i/pc_out
add wave -noupdate -divider IM
add wave -noupdate -radix unsigned /tb_minimicro/top_level/Instruction_memory_i/address
add wave -noupdate -radix hexadecimal -childformat {{{/tb_minimicro/top_level/Instruction_memory_i/instruction[15]} -radix hexadecimal} {{/tb_minimicro/top_level/Instruction_memory_i/instruction[14]} -radix hexadecimal} {{/tb_minimicro/top_level/Instruction_memory_i/instruction[13]} -radix hexadecimal} {{/tb_minimicro/top_level/Instruction_memory_i/instruction[12]} -radix hexadecimal} {{/tb_minimicro/top_level/Instruction_memory_i/instruction[11]} -radix hexadecimal} {{/tb_minimicro/top_level/Instruction_memory_i/instruction[10]} -radix hexadecimal} {{/tb_minimicro/top_level/Instruction_memory_i/instruction[9]} -radix hexadecimal} {{/tb_minimicro/top_level/Instruction_memory_i/instruction[8]} -radix hexadecimal} {{/tb_minimicro/top_level/Instruction_memory_i/instruction[7]} -radix hexadecimal} {{/tb_minimicro/top_level/Instruction_memory_i/instruction[6]} -radix hexadecimal} {{/tb_minimicro/top_level/Instruction_memory_i/instruction[5]} -radix hexadecimal} {{/tb_minimicro/top_level/Instruction_memory_i/instruction[4]} -radix hexadecimal} {{/tb_minimicro/top_level/Instruction_memory_i/instruction[3]} -radix hexadecimal} {{/tb_minimicro/top_level/Instruction_memory_i/instruction[2]} -radix hexadecimal} {{/tb_minimicro/top_level/Instruction_memory_i/instruction[1]} -radix hexadecimal} {{/tb_minimicro/top_level/Instruction_memory_i/instruction[0]} -radix hexadecimal}} -subitemconfig {{/tb_minimicro/top_level/Instruction_memory_i/instruction[15]} {-height 15 -radix hexadecimal} {/tb_minimicro/top_level/Instruction_memory_i/instruction[14]} {-height 15 -radix hexadecimal} {/tb_minimicro/top_level/Instruction_memory_i/instruction[13]} {-height 15 -radix hexadecimal} {/tb_minimicro/top_level/Instruction_memory_i/instruction[12]} {-height 15 -radix hexadecimal} {/tb_minimicro/top_level/Instruction_memory_i/instruction[11]} {-height 15 -radix hexadecimal} {/tb_minimicro/top_level/Instruction_memory_i/instruction[10]} {-height 15 -radix hexadecimal} {/tb_minimicro/top_level/Instruction_memory_i/instruction[9]} {-height 15 -radix hexadecimal} {/tb_minimicro/top_level/Instruction_memory_i/instruction[8]} {-height 15 -radix hexadecimal} {/tb_minimicro/top_level/Instruction_memory_i/instruction[7]} {-height 15 -radix hexadecimal} {/tb_minimicro/top_level/Instruction_memory_i/instruction[6]} {-height 15 -radix hexadecimal} {/tb_minimicro/top_level/Instruction_memory_i/instruction[5]} {-height 15 -radix hexadecimal} {/tb_minimicro/top_level/Instruction_memory_i/instruction[4]} {-height 15 -radix hexadecimal} {/tb_minimicro/top_level/Instruction_memory_i/instruction[3]} {-height 15 -radix hexadecimal} {/tb_minimicro/top_level/Instruction_memory_i/instruction[2]} {-height 15 -radix hexadecimal} {/tb_minimicro/top_level/Instruction_memory_i/instruction[1]} {-height 15 -radix hexadecimal} {/tb_minimicro/top_level/Instruction_memory_i/instruction[0]} {-height 15 -radix hexadecimal}} /tb_minimicro/top_level/Instruction_memory_i/instruction
add wave -noupdate -radix hexadecimal /tb_minimicro/top_level/Instruction_memory_i/im_mem
add wave -noupdate -divider RF
add wave -noupdate /tb_minimicro/top_level/RF_i/clk
add wave -noupdate /tb_minimicro/top_level/RF_i/rst_n
add wave -noupdate /tb_minimicro/top_level/RF_i/we
add wave -noupdate -radix unsigned /tb_minimicro/top_level/RF_i/rs1
add wave -noupdate -radix unsigned /tb_minimicro/top_level/RF_i/rs2
add wave -noupdate -radix unsigned /tb_minimicro/top_level/RF_i/rd
add wave -noupdate -radix decimal /tb_minimicro/top_level/RF_i/d
add wave -noupdate -radix decimal /tb_minimicro/top_level/RF_i/qs1
add wave -noupdate -radix decimal /tb_minimicro/top_level/RF_i/qs2
add wave -noupdate -radix decimal -childformat {{{/tb_minimicro/top_level/RF_i/rf_reg[0]} -radix decimal} {{/tb_minimicro/top_level/RF_i/rf_reg[1]} -radix decimal} {{/tb_minimicro/top_level/RF_i/rf_reg[2]} -radix decimal} {{/tb_minimicro/top_level/RF_i/rf_reg[3]} -radix decimal} {{/tb_minimicro/top_level/RF_i/rf_reg[4]} -radix decimal} {{/tb_minimicro/top_level/RF_i/rf_reg[5]} -radix decimal} {{/tb_minimicro/top_level/RF_i/rf_reg[6]} -radix decimal} {{/tb_minimicro/top_level/RF_i/rf_reg[7]} -radix decimal} {{/tb_minimicro/top_level/RF_i/rf_reg[8]} -radix decimal} {{/tb_minimicro/top_level/RF_i/rf_reg[9]} -radix decimal} {{/tb_minimicro/top_level/RF_i/rf_reg[10]} -radix decimal} {{/tb_minimicro/top_level/RF_i/rf_reg[11]} -radix decimal} {{/tb_minimicro/top_level/RF_i/rf_reg[12]} -radix decimal} {{/tb_minimicro/top_level/RF_i/rf_reg[13]} -radix decimal} {{/tb_minimicro/top_level/RF_i/rf_reg[14]} -radix decimal} {{/tb_minimicro/top_level/RF_i/rf_reg[15]} -radix decimal}} -expand -subitemconfig {{/tb_minimicro/top_level/RF_i/rf_reg[0]} {-height 15 -radix decimal} {/tb_minimicro/top_level/RF_i/rf_reg[1]} {-height 15 -radix decimal} {/tb_minimicro/top_level/RF_i/rf_reg[2]} {-height 15 -radix decimal} {/tb_minimicro/top_level/RF_i/rf_reg[3]} {-height 15 -radix decimal} {/tb_minimicro/top_level/RF_i/rf_reg[4]} {-height 15 -radix decimal} {/tb_minimicro/top_level/RF_i/rf_reg[5]} {-height 15 -radix decimal} {/tb_minimicro/top_level/RF_i/rf_reg[6]} {-height 15 -radix decimal} {/tb_minimicro/top_level/RF_i/rf_reg[7]} {-height 15 -radix decimal} {/tb_minimicro/top_level/RF_i/rf_reg[8]} {-height 15 -radix decimal} {/tb_minimicro/top_level/RF_i/rf_reg[9]} {-height 15 -radix decimal} {/tb_minimicro/top_level/RF_i/rf_reg[10]} {-height 15 -radix decimal} {/tb_minimicro/top_level/RF_i/rf_reg[11]} {-height 15 -radix decimal} {/tb_minimicro/top_level/RF_i/rf_reg[12]} {-height 15 -radix decimal} {/tb_minimicro/top_level/RF_i/rf_reg[13]} {-height 15 -radix decimal} {/tb_minimicro/top_level/RF_i/rf_reg[14]} {-height 15 -radix decimal} {/tb_minimicro/top_level/RF_i/rf_reg[15]} {-height 15 -radix decimal}} /tb_minimicro/top_level/RF_i/rf_reg
add wave -noupdate -divider Control
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/flags
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/op_code
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/branch
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/alu_op
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/writeback_sel
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/rtype_sel
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/dm_we
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/rf_we
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/pc_sel
add wave -noupdate /tb_minimicro/top_level/Control_unit_i/rs2_sel
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {262500 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 296
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1050 ns}
